### ISSUE TITLE
Loosing Blur when image is set programmatically 

### ISSUE THREAD

**Issue by thalisvilela** [egslava/BlurredImageView#1]
Hello! Could you help me work a way around this? When the resource is set programmatically (through setImageResource() or using Picasso) the blur doesn't apply. Thanks in advance.

**Comment by egslava** [comment]
Hi! I'm sorry to ask you, but, are you sure that you need dynamical blur in your case? Should your user to have a possibility to change the blurriness of an image in runtime?

**Comment by thalisvilela** [comment]
Hi! Thanks for the quick reply! The thing is, the image that needs to be blurred is comming from the webservice, so i need to set it programmatically. I figured that if i call setRadius() after the image is loaded the blur is applied. I guess if we set isBlurred to false when the image is changed/set, it will work. Is that correct?

**Comment by thalisvilela** [comment]
Yep! If i call `myBlurredImageView.isBlurred = false` before calling Picasso.load() or setImageResource(), the blur works just fine.

**Comment by egslava** [comment]
@thalisvilela no, I asked you a bit another question :-) You answered me that you need a dynamical image, I asked you about dynamical blur :-)

I mean, for instance, sometimes, you can use static blur: download an image, blur it in another thread, *cache blurred image* and, when you will use this image next time - it'll be taken already blurred from the cache. That's exactly what Picasso is designed for :-)

But sometimes you need to apply blur dynamically. For instance, you have a photo as a background in profile and want to blur it with slight animations super quick and fast. That's what this library is designed for :-)

Actually, you reported the bug, I think. But I'd like to know why how do you want to use it - should I be in hurry with it or I can just give you some code for Picasso :-)

**Comment by egslava** [comment]
For static blur this library should fit better :-)
https://github.com/wasabeef/picasso-transformations

**Comment by thalisvilela** [comment]
@egslava thank you very much! The real problem is, working 14 hours per day, i totally missed the correct approuch to give the image view an already blurred bitmap. You are 100% correct, i'm just using a fixed blur ammount just for "layout and design purposes". no need for a dynamic blur library. Thanks a lot! 

PS: I'm using your library anyway! :¬]

**Comment by egslava** [comment]
You're very welcome :-D Thank you for the kind response. I'd also be glad to work 14h/day, but, currently, I don't. So if you/your friends now have some ideas to implement - I'm ready to help them :-) It would be nice if you spread it a bit :-) Thank you very much! :-)
